### ISSUE TITLE
Return value of running() func always true

### ISSUE THREAD

**Issue by Saxin** [GyverLibs/GyverBlinker#1]
Thanks a lot for your libraries, they are great.
I encounter a problem, seems that the running() function always return **true**, regardless of led blinking.

I expect that when LED blinks the function will return **true**, otherwise **false**.
In the code block below btnFold is working vs. btnUnfold which doesn't work due to !stLed.running()

**Init section:**
```
// Buttons and LEDS
#define BTN_FOLD 18
#define BTN_UNFOLD 19
#define STAT_LED 13

Button btnFold(BTN_FOLD,INPUT);
Button btnUnfold(BTN_UNFOLD,INPUT);
Blinker stLed(STAT_LED); 
```

**Code Block:**
```
if (currentTimeUS - lastAxisUpdateTimeUS >= 25) {
      btnFold.tick();
      btnUnfold.tick();
      stLed.tick();
      if (btnUnfold.click() && !stLed.running()){
        stLed.blink(5,500,600);
      }
      if (btnFold.click()){
        stLed.blink(3,500,600);
      }
       // X_Axis->update();
       // Y_Axis->update();
      lastAxisUpdateTimeUS = currentTimeUS;
}
```

WOKWIKI test code - https://wokwi.com/projects/400508610403255297

**Comment by GyverLibs** [comment]
fixed. Thanks!

**Comment by Saxin** [comment]
Thank you, great libraries.
